Export SarifLog from index.ts (#28)
#### Description of changes

Type `SarifLog` is not exported from index.ts, meaning code example in README.md won't build.

```
error TS2305: Module '"node_modules/axe-sarif-converter/dist/index"' has no
exported member 'SarifLog'.

import { convertAxeToSarif, SarifLog } from 'axe-sarif-converter';
```

To make it build, `SarifLog` needs to be exported from package level (index.ts).

(Also fixed version in package-lock.json)

#### Pull request checklist

- [x] Added relevant unit test for your changes. (`npm run test`)